# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.7-dev

install:
  - pip install -r app/requirements.txt

script:
  - pytest

services:
  - docker

before_install:
  - docker build app -t coeus77/echo